require 'byebug'
require 'faraday'
require 'json'
require 'jsonpath'
require 'yaml'

task default: [:download, :rewrite]

task :download do
  response = Faraday.new('http://webconcepts.info').get('/specs.json')
  raise "Cannot download webconcepts/specs.json" unless response.success?
  File.write('tmp/specs.json', response.body)
end

task :rewrite do

  interest = YAML.load(File.read('./_data/interest.yml'))
  data = JSON.parse(File.read('./tmp/specs.json'))

  # Grab the specs from specs.json
  relevant = data.flat_map do |wg|
    wg_code, wg_data = wg
    groups_interested_specs = interest['webconcepts'][wg_code]
    # Dont want anything from these folks right now
    next if groups_interested_specs.nil?

    found_specs = groups_interested_specs.map do |interested_spec|
      spec = JsonPath.new(interested_spec['path']).first(wg_data)

      raise "No data found for #{interested_spec['path']}" if spec.nil?

      spec['wg'] = {
        'URL' => wg_data['id'],
        'short' => wg_data['short']
      }

      spec
    end

    puts "Found #{found_specs.length} specs for #{wg_code}"

  end

  # Add our own standards in
  relevant += interest['custom']

  relevant.sort_by do |spec|
    spec['title'] unless spec['title'].nil?
  end

  File.write('_data/standards.yml', "# Generated by Rakefile, please do not edit\n\n" + YAML.dump(relevant))
end
